version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-blockchain_news}
      POSTGRES_USER: ${DB_USER:-blockchain_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_blockchain_2024}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - blockchain-network

  blockchain-news:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-blockchain_news}
      - DB_USER=${DB_USER:-blockchain_admin}
      - DB_PASSWORD=${DB_PASSWORD:-secure_blockchain_2024}
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production}
      - FLASK_ENV=${FLASK_ENV:-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "${APP_PORT:-5000}:5000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - blockchain-network
    restart: unless-stopped

networks:
  blockchain-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
